# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
# -- Path setup --------------------------------------------------------------
# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
import sys

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath("../.."))
sys.setrecursionlimit(1500)


def setup(app):
    app.add_css_file('css/custom.css')
    app.add_css_file('css/hacks.css')


# -- Project information -----------------------------------------------------

project = 'KAN Imagery Catalog'
copyright = '2023'
author = 'Fernando D. Gómez :: Kan Territory & IT'

# The full version, including alpha/beta/rc tags
release = 'v0.1.3'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'autoapi.extension',
    'sphinx.ext.napoleon',
    'sphinx.ext.doctest',
    'sphinx.ext.viewcode',
    'docxsphinx',
]
autosummary_generate = True  # Turn on sphinx.ext.autosummary

autoapi_dirs = [
    '../../src',
]
autoapi_ignore = [
    '**/test',
    '**/docs',
    '**/conf.py',
    '**/test_up42.py',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'


# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['**/test']


# -- Options for HTML output -------------------------------------------------
html_theme = 'renku'


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_logo = 'logo_kan.png'
latex_logo = 'logo_kan.png'
rst_epilog = '\n.. include:: /.special.rst\n'
