# -*- coding: utf-8 -*-

# KAN Imagery Catalog QGIS plugin
# Satellite image catalog manager

# * Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
# * begin      : 2023-07-14
# * copyright  : (C) 2023 by KAN Territory & IT


# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.


"""
This script initializes the plugin, making it known to QGIS.
"""

import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent))


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load KANImageryCatalog class from file KANImageryCatalog.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # pylint: disable=invalid-name
    # pylint: disable=import-outside-toplevel
    # pylint: disable=unused-import

    from .kan_imagery_catalog import KANImageryCatalog

    return KANImageryCatalog(iface)
